train_dataset:
  name: panocity
  root_path:
  list_path:
  args:
    height: 512
    width: 1024
    repeat: 1
    augment_color: True
    augment_flip: True
    augment_rotation: True
  batch_size: 4
  num_workers: 8

val_dataset:
  name: panocity
  root_path:
  list_path:
  args:
    height: 512
    width: 1024
    repeat: 1
    augment_color: False
    augment_flip: False
    augment_rotation: False
    depth_scale: 1000.0
    max_depth_meters: 100.0
  batch_size: 1
  num_workers: 8

model:
  name: dap
  args:
    midas_model_type: vitl
    fine_tune_type:
    min_depth: 0.001
    max_depth: 1.0
    train_decoder: True

optimizer:
  lr: 1.e-4
  weight_decay: 0.01
epoch_max: 20
walltime_hours: 24
hardware:
  gpus: 4
  gpu_model: rtx_5000

loss:
  l1_weight: 1.0
  gradient_weight: 1.0

amp: True
load_weights_dir:
