defaults:
  - panocity_4rtx5000
  - _self_

exp_name: panocity_multi_4rtx5000
max_img_per_gpu: 2
max_img_per_gpu_val: 2
limit_val_batches: 20
val_epoch_freq: 999999

model:
  enable_camera: true
  enable_global_points: true

data:
  train:
    common_config:
      img_nums: [2, 2]
      max_img_per_gpu: ${max_img_per_gpu}
  val:
    common_config:
      img_nums: [2, 2]

loss:
  camera_weight: 0.1

