import os, time, json, tempfile
from contextlib import contextmanager

@contextmanager
def _exclusive_lock(lock_path, poll_interval=0.1, timeout=600):
    # Acquire lock atomically with O_CREAT|O_EXCL.
    start = time.time()
    fd = None
    try:
        while True:
            try:
                fd = os.open(lock_path, os.O_CREAT | os.O_EXCL | os.O_RDWR)
                break
            except FileExistsError:
                if time.time() - start > timeout:
                    raise TimeoutError(f"Timeout waiting for lock {lock_path}")
                time.sleep(poll_interval)
        yield
    finally:
        if fd is not None:
            os.close(fd)
            try:
                os.remove(lock_path)
            except FileNotFoundError:
                pass

def load_or_build_json_cache(cache_path, build_fn, poll_interval=0.2, timeout=900):
    """
    Load JSON cache if present, otherwise build it once with a lock.

    Flow:
    - Fast path: return existing cache.
    - Locked path: build and atomically publish cache.
    - Timeout path: wait for cache generated by another worker.
    """
    lock_path = cache_path + ".lock"
    if os.path.exists(cache_path):
        with open(cache_path, 'r') as f:
            return json.load(f)

    
    try:
        with _exclusive_lock(lock_path):
            
            if os.path.exists(cache_path):
                with open(cache_path, 'r') as f:
                    return json.load(f)
            data = build_fn()
            # Write temp file then atomically replace target.
            tmp = tempfile.NamedTemporaryFile(delete=False, dir=os.path.dirname(cache_path))
            try:
                with open(tmp.name, 'w') as f:
                    json.dump(data, f)
                os.replace(tmp.name, cache_path)
            finally:
                try:
                    os.unlink(tmp.name)
                except FileNotFoundError:
                    pass
            return data
    except TimeoutError:
        # Fallback: another worker likely builds the cache.
        start = time.time()
        while not os.path.exists(cache_path):
            if time.time() - start > timeout:
                raise TimeoutError(f"Timeout waiting for cache {cache_path}")
            time.sleep(poll_interval)
        with open(cache_path, 'r') as f:
            return json.load(f)